import { Playfair_Display } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import SmoothScrolling from '@/components/smoothscroll';
import Footer from '../components/footer';

const playfair = Playfair_Display({
	variable: '--font-playfair_display',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${playfair.variable}  antialiased`}>
				<Navbar />
				<SmoothScrolling>
					{children}
					<Footer />
				</SmoothScrolling>
			</body>
		</html>
	);
}

import { Playfair_Display } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import SmoothScrolling from '@/components/smoothscroll';
import Footer from '../components/footer';

const playfair = Playfair_Display({
	variable: '--font-playfair_display',
	subsets: ['latin'],
});

export const metadata = {
	title:
		'Edge Cleaning WA | Professional Deep Cleaning Services',
	description:
		'Professional deep cleaning in Washington. Eco-friendly, thorough, and reliable service for homes and businesses. Book your cleaning today!',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${playfair.variable}  antialiased`}>
				<Navbar />
				<SmoothScrolling>
					{children}
					<Footer />
				</SmoothScrolling>
			</body>
		</html>
	);
}
