import { Playfair_Display } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import SmoothScrolling from '@/components/smoothscroll';
import Footer from '../components/footer';

const playfair = Playfair_Display({
	variable: '--font-playfair_display',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${playfair.variable}  antialiased`}>
				<Navbar />
				<SmoothScrolling>
					{children}
					<Footer />
				</SmoothScrolling>
			</body>
		</html>
	);
}
